### ISSUE TITLE
Why are PYTHON defines explicit set to Python 3.7?

### ISSUE THREAD

**Issue by stertingen** [ros-melodic-arch/ros-build-tools-py3#1]
Why does every generated PKGBUILD have these four lines?

```
		-DPYTHON_EXECUTABLE=/usr/bin/python3 \
		-DPYTHON_INCLUDE_DIR=/usr/include/python3.7m \
		-DPYTHON_LIBRARY=/usr/lib/libpython3.7m.so \
		-DPYTHON_BASENAME=.cpython-37m \
```

(Last night there's been an update to Python 3.8; not only have some packages to be rebuilt, the PKGBUILD files of almost every ROS package are also outdated.)

**Comment by acxz** [comment]
This is a good observation, in my experience it seems like some packages use these flags while others do not.
We need to fix up our PKGBUILD generation pipeline for the new python (& maybe think about future proofing it for updates like the python 3.8 one).

As always it is about how much we commit towards fixing these issues. We would love PRs fixing these packages up. Right now I am trying to fix up the packages that break when I come across them, but I always have a hard time contributing as the semester starts closing up.
