### ISSUE TITLE
Why are tarballs not downloaded anymore?

### ISSUE THREAD

**Issue by jhbruhn** [ros-melodic-arch/ros-build-tools-py3#4]
I am currently using this script to generate PKGBUILDs for some ros-packages I am missing. But since a couple of commits, the tarballs are not downloaded by the PKGBUILD anyomore and thus the build fails as it has no source. Or am I missing something?

**Comment by acxz** [comment]
Can you clarify?

**Comment by jhbruhn** [comment]
I was trying to use the create_pkgbuild.py script to create PKGBUILDs, but the generated PKGBUILDs do not contain references to the tarballs of the package, thus they obviously fail to build. A previous version of the script did contain that, so i'm using that version, but the current revision does not any src files to the PKGBUILD: https://github.com/ros-melodic-arch/ros-build-tools-py3/blob/a336324142962f3040beba3d8000ce03b1682f24/create_pkgbuild.py#L239

**Comment by acxz** [comment]
ah yeah you are correct, it seems like this PR by major adds the source back in.

https://github.com/ros-melodic-arch/ros-build-tools-py3/pull/6/files#diff-abd42e8b23ecc34f0b44bea7c7d67a63R279-R281

**Comment by jhbruhn** [comment]
Great!
Are you using these scripts for the PKGBUILDs in this organization or are you using some other scripts to generate them? As in the state the script has in this repo it would not have generated the PKGBUILDs successfully i suppose.

**Comment by acxz** [comment]
I myself have not actually created ros PKGBUILDs in a long time (my role has mostly been reviewing and bugfixing). I don't recall ever using this script though. I think the other members have tho.

**Comment by bionade24** [comment]
> Great!
> Are you using these scripts for the PKGBUILDs in this organization or are you using some other scripts to generate them? As in the state the script has in this repo it would not have generated the PKGBUILDs successfully i suppose.

It's deprecated for a long time, IMHO it could be removed. But it's the only one we have which can create PKGBUILDs without any template to work on.

**Comment by acxz** [comment]
@jhbruhn We have moved the functionality of this repo into the following new place: https://github.com/ros-arch/ros-package-tools.
If you can create this issue over there that would be great. Closing this issue since ros-package-tools is the favored repository over this codebase.
