### ISSUE TITLE
Merge ros-build-tools-py3 with ros-build-tools

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-build-tools-py3#5]
I think having both packages is confusing for users. I think the updated ros-build scripts in this package should move over to [`ros-build-tools`](https://github.com/ros-melodic-arch/ros-build-tools). `ros-build-tools-py3` should be deprecated and we can create a `ros-build-tools-py2` for compatibility if needed. I think resolving this and keeping the latest changes on the original ros-build-tools will prevent users from installing the wrong version when installing the ROS stack.

**Comment by bionade24** [comment]
The problem is that the old ROS version link to ros-build-tools. Theoretically, this shouldn't be problematic as `ros-melodic-catkin` explicitely requires `ros-build-tools-py3`

**Comment by acxz** [comment]
Theoretically sure, but semantically it is nice to have the updated code live in `ros-build-tools` and instead have a `ros-build-tools-py2`.

**Comment by bionade24** [comment]
At the moment I think we just would break the other ROS distros here. ros-melodic-caktin can't be installed with `ros-build-tools` without manually editing the PKGBUILDs. https://aur.archlinux.org/packages/ros-melodic-catkin
A ros-build-tools-py2 would only possible if we edit all old distros. Maybe we can choose a different name, like ros-build-scripts.

**Comment by acxz** [comment]
When we create `ros-build-tools-py2` we can have it provide `ros-build-tools`. That solves the older distros using it.

**Comment by bionade24** [comment]
No, the people have to choose than manually to use the -py2 version.

**Comment by acxz** [comment]
And that is exactly what we are doing with py3 right now isnt it? Lets move that burden onto older distributions that will be EOL'd anyway.

**Comment by bionade24** [comment]
Now the PR still has to be resolved.

**Comment by acxz** [comment]
I have merged your commits on top of ros-build-tools. Since ros-build-tools is ROS distro agnostic I decided to place it within the ros-arch org [here](https://github.com/ros-arch) instead of either in ros-melodic-arch or ros-noetic-arch.
