### ISSUE TITLE
How to use create_pkgbuild.py?

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-melodic-arch/ros-build-tools-py3#7]
I want to make AUR noetic package for [imu_tools](https://wiki.ros.org/imu_tools?distro=noetic).

**Comment by bionade24** [comment]
It's deprecated and shouldn't be used by anyone, because it code points to wrong URLs for the Tarballs. 
If you need a package for noetic, request it in an issue at `ros-noetic-desktop-full`. 
@acxz  and the whole community will be glad if there stays one managing point.
